spring.application.name=mycoolapp

# configure server port
server.port=8484

#configure my props
coach.name=Mickey Mouse
team.name=The Mouse Crew

management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,beans,mappings
#auditevents - 404

management.info.env.enabled=true
info.app.name=My Super Cool App
info.app.description=A crazy fun app, yahoo!
info.app.version=1.0.0